// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2o7CGlYwMl8v7w_XNg3mtxGcOQjRJBgw',
    appId: '1:952995969220:web:6c32c195916a2556fbf191',
    messagingSenderId: '952995969220',
    projectId: 'ls-exclusif',
    authDomain: 'ls-exclusif.firebaseapp.com',
    storageBucket: 'ls-exclusif.firebasestorage.app',
    measurementId: 'G-K5X5RMC8TE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACkSknHfVNiPIjO1tbzp_RUdG-Vq-vDPY',
    appId: '1:952995969220:android:bf7ccc7e0edf7569fbf191',
    messagingSenderId: '952995969220',
    projectId: 'ls-exclusif',
    storageBucket: 'ls-exclusif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdXkZUWxnNkKDbxDItMRjRtLpkdsjEgI',
    appId: '1:952995969220:ios:6dacdfd5864b4fccfbf191',
    messagingSenderId: '952995969220',
    projectId: 'ls-exclusif',
    storageBucket: 'ls-exclusif.firebasestorage.app',
    iosBundleId: 'com.example.appLs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdXkZUWxnNkKDbxDItMRjRtLpkdsjEgI',
    appId: '1:952995969220:ios:6dacdfd5864b4fccfbf191',
    messagingSenderId: '952995969220',
    projectId: 'ls-exclusif',
    storageBucket: 'ls-exclusif.firebasestorage.app',
    iosBundleId: 'com.example.appLs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2o7CGlYwMl8v7w_XNg3mtxGcOQjRJBgw',
    appId: '1:952995969220:web:47ede6fdfb5257d9fbf191',
    messagingSenderId: '952995969220',
    projectId: 'ls-exclusif',
    authDomain: 'ls-exclusif.firebaseapp.com',
    storageBucket: 'ls-exclusif.firebasestorage.app',
    measurementId: 'G-K5LGZ68XJX',
  );
}
